name: Test

on:
  push:
    branches: [ main ]

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Say Hello
      uses: philiprbrenan/testPackage@main
      with:
        who-to-greet: "Every-one"
